INSERT INTO registro_usuarios (
    nombre,
    apellido,
    correo,
    documento,
    telefono,
    nombre_usuario,
    pass_hash,
    tipo_usuario,
    curso,
    materia,
    nombre_estudiante,
    codigo_docente_asignado,
    codigo_docente_referencia,
    creado_en
)
VALUES
    (
        'Admin',
        'Test',
        'admin@classify.local',
        'TEST-ADM-BASE',
        '3000000001',
        'admin',
        '$2y$10$IQMkN2GaYiKq908CK0aju.Z9GFBe981aHlGhI7aDCnu3CtN8UQjLK',
        'administrador',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        'Docente',
        'Test',
        'docente@classify.local',
        'TEST-DOC-BASE',
        '3000000002',
        'docente',
        '$2y$10$IQMkN2GaYiKq908CK0aju.Z9GFBe981aHlGhI7aDCnu3CtN8UQjLK',
        'docente',
        NULL,
        'Ciencias Naturales',
        NULL,
        'DOC-BASE01',
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        'Estudiante',
        'Test',
        'estudiante@classify.local',
        'TEST-EST-BASE',
        '3000000003',
        'estudiante',
        '$2y$10$IQMkN2GaYiKq908CK0aju.Z9GFBe981aHlGhI7aDCnu3CtN8UQjLK',
        'estudiante',
        '7A',
        NULL,
        NULL,
        NULL,
        NULL,
        CURRENT_TIMESTAMP
    ),
    (
        'Acudiente',
        'Test',
        'acudiente@classify.local',
        'TEST-ACU-BASE',
        '3000000004',
        'acudiente',
        '$2y$10$IQMkN2GaYiKq908CK0aju.Z9GFBe981aHlGhI7aDCnu3CtN8UQjLK',
        'acudiente',
        NULL,
        NULL,
        'Estudiante Demo',
        NULL,
        NULL,
        CURRENT_TIMESTAMP
    )
ON CONFLICT (nombre_usuario)
DO UPDATE SET
    nombre = EXCLUDED.nombre,
    apellido = EXCLUDED.apellido,
    correo = EXCLUDED.correo,
    documento = EXCLUDED.documento,
    telefono = EXCLUDED.telefono,
    pass_hash = EXCLUDED.pass_hash,
    tipo_usuario = EXCLUDED.tipo_usuario,
    curso = EXCLUDED.curso,
    materia = EXCLUDED.materia,
    nombre_estudiante = EXCLUDED.nombre_estudiante,
    codigo_docente_asignado = EXCLUDED.codigo_docente_asignado,
    codigo_docente_referencia = EXCLUDED.codigo_docente_referencia;
