spring.application.name=classify2.0
classify.webhooks.welcome.url=https://n8n.classify.in.net/webhook/a54058de-22a2-488b-956c-21bc5520d6a0

# Webhook Contacta un Profe
classify.webhooks.contacta.url=https://n8n.classify.in.net/webhook/b6400a0a-053a-4aa1-b389-56eaec481db4

# Webhook Contacto General (Landing) - PRODUCCIÓN (Activo)
classify.webhooks.contacto.url=https://n8n.classify.in.net/webhook/1b573e49-3bdc-4985-a993-ff2798735d57

#No tocar
spring.web.resources.static-locations=classpath:/static/
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
