spring.application.name=classify2.0
classify.webhooks.welcome.url=https://n8n.classify.in.net/webhook/a54058de-22a2-488b-956c-21bc5520d6a0

#No tocar
spring.web.resources.static-locations=classpath:/static/
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
