package com.classify20.service;

import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;

@Service
public class ClassifyDatabaseService {

    private static final Logger logger = LoggerFactory.getLogger(ClassifyDatabaseService.class);

    private static final String CREATE_TABLE_SQL = """
            CREATE TABLE IF NOT EXISTS registro_usuarios (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre VARCHAR(120) NOT NULL,
                apellido VARCHAR(120) NOT NULL,
                correo VARCHAR(180) NOT NULL UNIQUE,
                documento VARCHAR(40) NOT NULL UNIQUE,
                telefono VARCHAR(30) NOT NULL,
                nombre_usuario VARCHAR(100) NOT NULL UNIQUE,
                pass_hash VARCHAR(255) NOT NULL,
                tipo_usuario VARCHAR(20) NOT NULL,
                curso VARCHAR(50),
                materia VARCHAR(150),
                nombre_estudiante VARCHAR(150),
                codigo_docente_asignado VARCHAR(20) UNIQUE,
                codigo_docente_referencia VARCHAR(20),
                creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """;

    private static final String CREATE_INDEX_TYPE_SQL = """
            CREATE INDEX IF NOT EXISTS idx_registro_usuarios_tipo
            ON registro_usuarios (tipo_usuario)
            """;

    private static final String CREATE_INDEX_CODE_SQL = """
            CREATE INDEX IF NOT EXISTS idx_registro_usuarios_codigo_ref
            ON registro_usuarios (codigo_docente_referencia)
            """;

    private static final String FIND_BY_USERNAME_SQL = """
            SELECT id
            FROM registro_usuarios
            WHERE nombre_usuario = ?
            LIMIT 1
            """;

    private static final String INSERT_USER_SQL = """
            INSERT INTO registro_usuarios (
                nombre,
                apellido,
                correo,
                documento,
                telefono,
                nombre_usuario,
                pass_hash,
                tipo_usuario,
                curso,
                materia,
                nombre_estudiante,
                codigo_docente_asignado,
                codigo_docente_referencia,
                creado_en
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """;

    private static final String UPDATE_USER_SQL = """
            UPDATE registro_usuarios
            SET nombre = ?,
                apellido = ?,
                correo = ?,
                documento = ?,
                telefono = ?,
                pass_hash = ?,
                tipo_usuario = ?,
                curso = ?,
                materia = ?,
                nombre_estudiante = ?,
                codigo_docente_asignado = ?,
                codigo_docente_referencia = ?,
                creado_en = ?
            WHERE nombre_usuario = ?
            """;

    private static final List<SeedUser> TEST_USERS = List.of(
            new SeedUser("Admin", "Test", "admin@classify.local", "TEST-ADM-BASE", "3000000001",
                    "admin", "administrador", null, null, null, null, null),
            new SeedUser("Docente", "Test", "docente@classify.local", "TEST-DOC-BASE", "3000000002",
                    "docente", "docente", null, "Ciencias Naturales", null, "DOC-BASE01", null),
            new SeedUser("Estudiante", "Test", "estudiante@classify.local", "TEST-EST-BASE", "3000000003",
                    "estudiante", "estudiante", "7A", null, null, null, null),
            new SeedUser("Acudiente", "Test", "acudiente@classify.local", "TEST-ACU-BASE", "3000000004",
                    "acudiente", "acudiente", null, null, "Estudiante Demo", null, null)
    );

    private final String primaryUrl;
    private final String primaryUsername;
    private final String primaryPassword;
    private final String fallbackUrl;
    private final String fallbackUsername;
    private final String fallbackPassword;
    private final PasswordEncoder passwordEncoder;
    private final String testPasswordHash;

    private volatile ConnectionSettings activeSettings;

    public ClassifyDatabaseService(
            @Value("${classify.db.url:jdbc:postgresql://localhost:5432/classify}") String primaryUrl,
            @Value("${classify.db.username:postgres}") String primaryUsername,
            @Value("${classify.db.password:postgres}") String primaryPassword,
            @Value("${classify.db.fallback-url:jdbc:h2:file:./.classify-data/classify;MODE=PostgreSQL;AUTO_SERVER=TRUE;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}") String fallbackUrl,
            @Value("${classify.db.fallback-username:sa}") String fallbackUsername,
            @Value("${classify.db.fallback-password:}") String fallbackPassword) {
        this.primaryUrl = primaryUrl;
        this.primaryUsername = primaryUsername;
        this.primaryPassword = primaryPassword;
        this.fallbackUrl = fallbackUrl;
        this.fallbackUsername = fallbackUsername;
        this.fallbackPassword = fallbackPassword;
        this.passwordEncoder = new BCryptPasswordEncoder();
        this.testPasswordHash = passwordEncoder.encode("12345");
    }

    @PostConstruct
    void initialize() {
        try {
            ensureReady();
        } catch (SQLException exception) {
            logger.error("No fue posible inicializar la base de datos de Classify.", exception);
        }
    }

    public Connection openConnection() throws SQLException {
        try {
            ConnectionSettings settings = ensureReady();
            Connection connection = DriverManager.getConnection(settings.url(), settings.username(), settings.password());
            ensureSchemaAndSeed(connection);
            return connection;
        } catch (SQLException primaryException) {
            if (activeSettings == null || activeSettings.fallback()) {
                throw primaryException;
            }

            logger.warn("Fallo la conexion a la base primaria. Se intentara la base embebida.", primaryException);
            synchronized (this) {
                activeSettings = fallbackSettings();
            }

            ConnectionSettings fallback = ensureReady();
            Connection connection = DriverManager.getConnection(fallback.url(), fallback.username(), fallback.password());
            ensureSchemaAndSeed(connection);
            return connection;
        }
    }

    public synchronized ConnectionSettings ensureReady() throws SQLException {
        if (activeSettings != null) {
            return activeSettings;
        }

        try (Connection connection = DriverManager.getConnection(primaryUrl, primaryUsername, primaryPassword)) {
            ensureSchemaAndSeed(connection);
            activeSettings = primarySettings();
            logger.info("Classify usara la base de datos principal: {}", primaryUrl);
            return activeSettings;
        } catch (SQLException exception) {
            logger.warn("No fue posible conectar con la base primaria {}. Se utilizara una base embebida local.",
                    primaryUrl);
            try (Connection connection = DriverManager.getConnection(fallbackUrl, fallbackUsername, fallbackPassword)) {
                ensureSchemaAndSeed(connection);
                activeSettings = fallbackSettings();
                logger.info("Classify usara la base de datos embebida: {}", fallbackUrl);
                return activeSettings;
            }
        }
    }

    private void ensureSchemaAndSeed(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(CREATE_TABLE_SQL);
            statement.execute(CREATE_INDEX_TYPE_SQL);
            statement.execute(CREATE_INDEX_CODE_SQL);
        }

        for (SeedUser user : TEST_USERS) {
            upsertUser(connection, user);
        }
    }

    private void upsertUser(Connection connection, SeedUser user) throws SQLException {
        boolean exists;

        try (PreparedStatement statement = connection.prepareStatement(FIND_BY_USERNAME_SQL)) {
            statement.setString(1, user.username());
            try (ResultSet resultSet = statement.executeQuery()) {
                exists = resultSet.next();
            }
        }

        if (exists) {
            try (PreparedStatement statement = connection.prepareStatement(UPDATE_USER_SQL)) {
                statement.setString(1, user.name());
                statement.setString(2, user.lastName());
                statement.setString(3, user.email());
                statement.setString(4, user.document());
                statement.setString(5, user.phone());
                statement.setString(6, testPasswordHash);
                statement.setString(7, user.type());
                statement.setString(8, user.course());
                statement.setString(9, user.subject());
                statement.setString(10, user.studentName());
                statement.setString(11, user.teacherCode());
                statement.setString(12, user.teacherReference());
                statement.setTimestamp(13, Timestamp.valueOf(LocalDateTime.now()));
                statement.setString(14, user.username());
                statement.executeUpdate();
            }
            return;
        }

        try (PreparedStatement statement = connection.prepareStatement(INSERT_USER_SQL)) {
            statement.setString(1, user.name());
            statement.setString(2, user.lastName());
            statement.setString(3, user.email());
            statement.setString(4, user.document());
            statement.setString(5, user.phone());
            statement.setString(6, user.username());
            statement.setString(7, testPasswordHash);
            statement.setString(8, user.type());
            statement.setString(9, user.course());
            statement.setString(10, user.subject());
            statement.setString(11, user.studentName());
            statement.setString(12, user.teacherCode());
            statement.setString(13, user.teacherReference());
            statement.setTimestamp(14, Timestamp.valueOf(LocalDateTime.now()));
            statement.executeUpdate();
        }
    }

    private ConnectionSettings primarySettings() {
        return new ConnectionSettings(primaryUrl, primaryUsername, primaryPassword, false);
    }

    private ConnectionSettings fallbackSettings() {
        return new ConnectionSettings(fallbackUrl, fallbackUsername, fallbackPassword, true);
    }

    public record ConnectionSettings(String url, String username, String password, boolean fallback) {
    }

    private record SeedUser(
            String name,
            String lastName,
            String email,
            String document,
            String phone,
            String username,
            String type,
            String course,
            String subject,
            String studentName,
            String teacherCode,
            String teacherReference) {
    }
}
